-- MySQL Script generated by MySQL Workbench
-- Mon May 11 12:39:09 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `violation_location` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `vehicle_id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_make` VARCHAR(50) NOT NULL,
  `license_plate_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Time_of_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Time_of_day` (
  `time_of_day_id` INT NOT NULL AUTO_INCREMENT,
  `time_category` VARCHAR(45) NULL,
  PRIMARY KEY (`time_of_day_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`issuing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`issuing` (
  `issuing_id` INT NOT NULL AUTO_INCREMENT,
  `officer_id` VARCHAR(50) NOT NULL,
  `unit_description` VARCHAR(10) NOT NULL,
  `issued_by` VARCHAR(45) NULL,
  PRIMARY KEY (`issuing_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `ticket_number` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `time_of_day_id` INT NOT NULL,
  `issuing_id` INT NOT NULL,
  PRIMARY KEY (`ticket_number`),
  INDEX `fk_Ticket_Location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_Ticket_Vehicle1_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `fk_Ticket_Time_of_day1_idx` (`time_of_day_id` ASC) VISIBLE,
  INDEX `fk_Ticket_issuing1_idx` (`issuing_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Time_of_day1`
    FOREIGN KEY (`time_of_day_id`)
    REFERENCES `mydb`.`Time_of_day` (`time_of_day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_issuing1`
    FOREIGN KEY (`issuing_id`)
    REFERENCES `mydb`.`issuing` (`issuing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Violation_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Violation_types` (
  `violation_type_id` INT NOT NULL AUTO_INCREMENT,
  `violation_code` VARCHAR(20) NULL,
  `violation_description` VARCHAR(100) NULL,
  PRIMARY KEY (`violation_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fine` (
  `fine_id` INT NOT NULL AUTO_INCREMENT,
  `fine_level` INT NOT NULL,
  `fine_amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`fine_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `fine_id` INT NOT NULL,
  `current_amount_due` DECIMAL(10,2) NOT NULL,
  `total_payments` DECIMAL(10,2) NOT NULL,
  `payment_status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_Fine1_idx` (`fine_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Fine1`
    FOREIGN KEY (`fine_id`)
    REFERENCES `mydb`.`Fine` (`fine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket_Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket_Fine` (
  `ticket_number` INT NOT NULL,
  `fine_id` INT NOT NULL,
  INDEX `fk_Ticket_Fine_Fine1_idx` (`fine_id` ASC) VISIBLE,
  PRIMARY KEY (`ticket_number`, `fine_id`),
  CONSTRAINT `fk_Ticket_Fine_Ticket1`
    FOREIGN KEY (`ticket_number`)
    REFERENCES `mydb`.`Ticket` (`ticket_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Fine_Fine1`
    FOREIGN KEY (`fine_id`)
    REFERENCES `mydb`.`Fine` (`fine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket_Violation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket_Violation` (
  `ticket_number` INT NOT NULL,
  `violation_type_id` INT NOT NULL,
  INDEX `fk_Ticket_Violation_Ticket1_idx` (`ticket_number` ASC) VISIBLE,
  PRIMARY KEY (`ticket_number`, `violation_type_id`),
  INDEX `fk_Ticket_Violation_Violation_types1_idx` (`violation_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Violation_Violation_types1`
    FOREIGN KEY (`violation_type_id`)
    REFERENCES `mydb`.`Violation_types` (`violation_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Violation_Ticket1`
    FOREIGN KEY (`ticket_number`)
    REFERENCES `mydb`.`Ticket` (`ticket_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
